export const REGISTER = 'REGISTER';
export const REGISTER_SUCCEEDED = 'REGISTER_SUCCEEDED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const AUTHORIZE = 'AUTHORIZE';
export const SET_REWARDS_FILTER_STRING = 'SET_REWARDS_FILTER_STRING';
export const SET_USERS_FILTER_STRING = 'SET_USERS_FILTER_STRING';

export const FETCH_REWARDS = 'FETCH_REWARDS'
export const FETCH_REWARDS_SUCCEEDED = 'FETCH_REWARDS_SUCCEEDED'
export const FETCH_REWARDS_FAILED = 'FETCH_REWARDS_FAILED'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCEEDED = 'FETCH_USERS_SUCCEEDED'
export const FETCH_USERS_FAILED = 'FETCH_USERS_FAILED'